name: "build"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - name: "deps"
        run: apk add go make
      - name: "build"
        run: make
