name: "build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - name: "setup deps"
        run: "apk add make bash git go"
      - name: "build"
        run: make

