name: "build"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - name: "deps"
        run: apk add go meson samurai
      - name: "meson"
        run: meson setup build
      - name: "ninja"
        working-directory: build
        run: ninja

